[package]
name = "rate-my-politician"
version = "0.1.0"
description = "A Solana program for rating politicians with approve/disapprove voting"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "rate_my_politician"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"

[dev-dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }